# This workflow will run tests on push or PRs
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run lint
      - run: deno run test
